food/urls.py
from . import views
from django.urls import path


app_name ='food'
urlpatterns = [
    path('',views.IndexClassView.as_view(),name="index"),
    path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
    path('add',views.CreateItem.as_view(),name='create_item'),
    path('update/<int:id>/',views.update_item,name='update_item'),
    path('delete/<int:id>/',views.delete_item,name='delete_item'),
]

mysite/urls.py
from telnetlib import LOGOUT
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('food.urls')),
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),

]
urlpatterns += [

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from audioop import reverse
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
# Create your models here.
class Item(models.Model):

    def __str__(self):          #this will format the output in our pythom shell database in order to se the actual object name
        return self.item_name

    user_name=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name= models.CharField(max_length=200)
    item_desc= models.CharField(max_length=200)
    recipe = models.TextField(max_length=2000)#recepie field
    item_image = models.CharField(max_length=500,default="https://th.bing.com/th/id/OIP.ISK0kbvLUbQTc9hltD47fAHaF0?pid=ImgDet&rs=1")

    def get_absolute_url(self):
        return reverse("food:detail",kwargs={"pk":self.pk})

users/models.py
from distutils.command import upload
from email.mime import image
from email.policy import default
import profile
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profile.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)


    def __str__(self):
        return self.user.username

food/forms.py

from django import forms
from .models import Item 

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields =['item_name','item_desc','recipe','item_image']




users/forms.py
from dataclasses import fields
from pyexpat import model
from xml.dom import UserDataHandler
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class Register_form(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model=User
        fields =['username','email','password1','password2']



food/views.py
from ast import Delete
from multiprocessing import context
from re import template
from django.shortcuts import render,HttpResponse, redirect
from django.http import HttpResponse
from . models import Item
from django.template import loader
from .forms import ItemForm
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.core.exceptions import PermissionDenied

def edit(request, pk):
    if not request.user.is_staff:
        raise PermissionDenied

# Create your views here.
 
'''def index(request):
    item_list =  Item.objects.all()
    context={
        'item_list':item_list,
        
     }
    return render(request,'food/index.html',context)

WE HAVE REPLACE THIS WITH IndexCassView.

'''

class IndexClassView(ListView):
    model = Item;
    template_name='food/index.html'
    context_object_name = 'item_list'





'''def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
           'item':item,
        }
    return render(request,'food/detail.html',context)
    
WE HAVE REPLACE THIS FUNCTION WITH FoodDetail CLASS.
'''


class FoodDetail(DetailView):
    model= Item
    template_name= 'food/detail.html'



'''@login_required
def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form})
    
THIS WAS REPLACE WITH CreateItem CLASS
'''

class CreateItem(CreateView):
    model= Item;
    fields = ['item_name','item_desc','recipe','item_image']
    template_name= 'food/item-form.html'



    def form_valid(self, form):
        form.instance.user_name=self.request.user
        return super().form_valid(form)
    
    


@login_required
def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request,'food/item-form.html',{'form':form,'item':item})

@login_required
def delete_item(request,id):
    item = Item.objects.get(id=id)

    if not request.user.is_staff:
        raise PermissionDenied

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{'item':item})
    
 

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from . forms import Register_form
# Create your views here.
def register(request):
    if request.method == 'POST':
        form = Register_form(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}, Your account has been created')
            return redirect('login')
    else:
        form = Register_form()
    return render(request,'users/register.html', {'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<HEAD>
    <TITLE></TITLE>
    <link rel="shortcut icon" type="image/png" href="{% static 'cheff.png' %}" />
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    

</HEAD>
<body>
    <nav class="navbar navbar bg-info " id="nav">
        <div class="container-fluid">
            <a class="navbar-brand text-white" href="{% url 'food:index'%}"><img id="cheff" src="{% static 'food/cheff.png' %}" alt="Food app" /></a>
            <ul class="nav justify-content-end">
                <li class="nav-item">
                    <a class="nav-link active text-white" href="{% url 'register' %}" aria-current="page" href="#">Register</a>
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link text-white" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                    <a class="nav-link text-white" href="{% url 'login' %}">Login</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'profile' %}">Profile</a>

                </li>
                <li class="nav-item">
                    
                </li>
                
                <a class="nav-link text-white" href="{% url 'food:create_item'%}">Add Item</a>
            </ul>

    </nav>
    
    {% if messages %}

    {% for message in messages %}
    <div class="alert alert-{{message.tags}}">{{message}}</div>



    {% endfor %}

    {% endif %}
    {% block content %}




    {% endblock %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block content %}


<div class="container">
    <div class="row">
        <div class="col-md-6">
            <style>
            img {
            max-width:80%;
            height:auto;
            }
            </style>
            <img src="{{item.item_image}}" class="card" />
        </div>

        <div class="col-md-6">
            <h1>{{ object.item_name }}</h1>
            <h2>{{ object.item_desc }}</h2>
            <h3>{{ object.recipe }}</h3>
            <div class="col-md-2">
                <a href="{% url 'food:delete_item' item.id %}">Delete</a>
                <a href="{% url 'food:update_item' item.id %}">Edit</a>
            </div>
        </div>
    </div>
    
    </div>

{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE HTML>
<HTML lang="en">
<HEAD>
    <TITLE></TITLE>
    
    <BODY>


        {% block content %}

        {% for item in item_list %}
        <style>
        
        .card {
                max-width: 80%;
                height: auto;
                width: auto;
                text-align: center;
                padding: 20px;
                margin-top:20px;
            }
            .col-md-4 {
                margin-top: 20px;
            }
            
          
        </style>

        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="145px" src="{{item.item_image}}" />
            </div>
            <div class="col-md-4">
                <h3>{{item.item_name}}</h3>
                <h5>{{item.item_desc}}</h5>
                <h6>{{item.user_name}}</h6>        


            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-info text-white">Details</a>
                <style>
                    .btn {
                        margin: 20px;
                    }
                </style>
            </div>
        </div>



        {% endfor %}

        {% endblock %}
    </BODY>
</HTML>




food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}

    <h2>Are you sure you want to Delete {{item.item_name}}?</h2>
    <button type="submit">Confirm</button>

</form>

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block content %}

<style>
    .container {
        margin-top: 50px;
    }
</style>
<div class="container">
    <div class="row-2">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        My Recipe
                    </div>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{field.name}}
                            <br>
                            {{field}}

                        </div>

                        {% endfor %}
                        <button class="card bg-info text-white" type="submit">Submmit</button>

                    </form>

                </div>
            </div>

        </div>

    </div>
</div>



{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block content %}
<style>
    .container{

      margin-top:50px;
    }
</style>
<div class="container">
    <div class="row-2">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Login
                    </div>
                </div>
               <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{field.name}}
                               
                            {{field}}
                        </div>
                        {% endfor %}
                        <button class="card bg-info text-white " type="submit">Login</button>
                    </form>
                </div>
            </div>

        </div>

    </div>
</div>
{% endblock %}


users/templates/users/logout.html
<H1>You have succsessfuly logged out</H1>

users/templates/users/profile.html
<h1>{{user.username}}</h1>
<style>
    #prof {
        max-width: 200px;
        height: auto;
        width: auto;
        text-align: center;
        padding: 20px;
    }
</style>
<image id="prof" src="{{ user.profile.image.url }}"></image>

users/templates/users/register.html
{% extends 'food/base.html' %}
{% block content %}
<style>
    .container{

      margin-top:50px;
    }
    </style>
<div class="container">
    <div class="row-2">
        <div class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header text-white bg-info">
                    <div class="card-title">
                        Register
                    </div>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{field.name}}
                            <br>
                            {{field}}

                        </div>

                        {% endfor %}
                        <button class="card bg-info text-white" type="submit">register</button>

                    </form>

                </div>
            </div>

        </div>

    </div>
</div>
{% endblock %}




